// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmimjuoezczcmnczuvnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptaW1qdW9lemN6Y21uY3p1dm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDg4NTIsImV4cCI6MjA1NzQ4NDg1Mn0.qW3noDGo4oyPmAqqB-MNArgsVZ86oy3B2JCj-sLvtMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);